language: python
sudo: false
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
env:
    - PYRAMID_VER="==1.5" # test 1.5 series
install:
    - "python setup.py install"
    - "pip install tzf.pyramid_yml[tests] coveralls pylama pyramid$PYRAMID_VER"
    # manually install wheel for deployment
    - "pip install wheel"
script:
    - py.test --cov-report term-missing --cov tzf.pyramid_yml tests/
    - pylama
after_success:
    - coveralls

# deploy

deploy:
    provider: pypi
    user: fizyk
    password:
        secure: GMEtklbgirofHMeCDIZK+2B0h5/Y2nsLrgINPVnWyr7Vtt6vGuFSmT95nMJaFG7+H0y+K9AcHmME8g4bRL8Y7SKn06i5hfF32qAaSgqlwYyk41FPt6rIYh4wKwaVU499EdL3CrAUJpO4pPeKG3dZxcinNMIfuKIdVRxe7cBvBQg=
    on:
        tags: true
        all_branches: true
        repo: fizyk/pyramid_yml
    distributions: "sdist bdist_egg bdist_wheel"
