language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# blocklist branches
branches:
  except:
  - requires-io-master
  - /^dependabot.*$/
install:
  - "pip install -r requirements-test.txt"
  # manually install wheel for deployment
  - "pip install coveralls wheel"
script:
  - py.test --cov-report term-missing --cov tzf.pyramid_yml tests/
after_success:
  - coveralls
jobs:
  include:
  - stage: linters
    python: 3.6
    install:
    - pip install -r requirements-lint.txt
    script:
    - pycodestyle
    - pydocstyle
    - pylint tzf.pyramid_yml tests
    after_success: skip
  - stage: deploy
    python: 3.6
    if: tag IS present
    script: skip
    deploy:
      provider: pypi
      user: fizyk
      password:
        secure: GMEtklbgirofHMeCDIZK+2B0h5/Y2nsLrgINPVnWyr7Vtt6vGuFSmT95nMJaFG7+H0y+K9AcHmME8g4bRL8Y7SKn06i5hfF32qAaSgqlwYyk41FPt6rIYh4wKwaVU499EdL3CrAUJpO4pPeKG3dZxcinNMIfuKIdVRxe7cBvBQg=
      on:
        tags: true
        all_branches: true
        repo: fizyk/pyramid_yml
      distributions: "bdist_wheel"
